version: '3'

services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: always
    ports:
      - "8080:80" # Expose le service sur le port 8080
    volumes:
      - excalidraw_data:/data # Volume persistant pour les données
    environment:
      - NODE_ENV=production

volumes:
  excalidraw_data:
